### ISSUE TITLE
Install or Setup Guide

### ISSUE THREAD

**Issue by Btibert3** [Alexmhack/rasa-chat-sample#1]
I am not a developer by trade (more of a "data scientist") but I am very interested in how to leverage an interface for rasa.  That said, any help or guidance on how to get this up and running?  A quick start or install guide?  Thanks!

**Comment by Alexmhack** [comment]
[Webchat](https://github.com/mrbot-ai/rasa-webchat) has a nice interface for Rasa powered chat bot which displays texts, buttons, images, videos, links etc that are sent from rasa but it also involves use of a third party application which can easily watch over the data you send to it but they have done a pretty good job.

If you want to create your interface from ground up you can refer to their [code](https://github.com/mrbot-ai/rasa-webchat/tree/master/src/components/Widget/components/Conversation/components/Messages) and the responses that rasa sends when you call its server using JavaScript assuming you are looking for a web interface.

Rasa core server sends an array of objects in javaScript or dict in python containing texts, buttons, images so you can easily loop through the array and accordingly put html and css for the responses.

You can checkout [Django-Rasa-Bot](https://github.com/Alexmhack/Django-Rasa-Bot) & [Django-Rasa-Sockets](https://github.com/Alexmhack/Django-Rasa-Sockets) and also rasa [docs](https://rasa.com/docs/core/connectors/#rest-channels) mentions about widgets,

`If you want to put a widget on your website so that people can talk to your bot, check out these two projects:`

    Rasa Webchat uses sockets.
    Chatroom uses regular HTTP requests.

`For these use cases it is easiest to use either the RestInput or the CallbackInput channels. They will provide you with a URL to post the messages to.`

**Comment by Btibert3** [comment]
Thanks for the detailed response.  I was browsing to see what options existed out there, and came across your repo and thought this was a widget like those above and I wanted to play around.  I will check the other two out.
